version: "3.3"
services:
        servidor-nats:
                image: nats-proyecto
                command: nats
        aplicacion:
                build:
                        context: aplikazioa/
                        dockerfile: Dockerfile
                links:
                 - servidor-nats

                volumes:
                 - ./python:/app:rw
volumes:
        volPython: