version: "3.6"
services:
        servidor-nats:
                image: nats:latest
                container_name: servidor-nats
                expose:
                        - "4222"
                ports:
                        - 4222:4222

        app:
                build: dockerErabiltzailea/
                container_name: app-nats
                depends_on:
                        - servidor-nats
                stdin_open: true
                tty: true



