apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app
      volumeMounts:
        - mountPath: app
          name: volpython
  volumes:
    - name: volPython
      persistentVolumeClaim:
        claimName: volpython